import '../styles/index.css'
import { ReactNode } from 'react'

import { ThemesProvider } from '@/hooks/useTheme'
import { UserProvider } from '@/hooks/useUser'
import { Inter } from 'next/font/google'

import { ConfirmationModalControl } from './(global)/ConfirmationModalControl'
import { LoadingControl } from './(global)/LoadingControl'
import { MainSidebar } from './(global)/MainSidebar'
import { SnackbarControl } from './(global)/SnackbarControl'
import { Header } from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Home | Cards Quiz',
    template: '%s | Cards Quiz'
  },
  description: 'Generated by test Cards Quiz'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${inter.className} h-full scroll-smooth antialiased`}>
      <body className="bg-light text-dark dark:bg-dark dark:text-light" suppressHydrationWarning>
        <ThemesProvider>
          <UserProvider>
            <div
              id="app"
              className="fixed inset-0 overflow-auto scrollbar scrollbar-track-white/75 scrollbar-thumb-[#8888884b] dark:scrollbar-track-zinc-700"
            >
              <Header />
              <MainSidebar />
              <div className="h-[calc(100%-56px)] px-5 py-5 sm:px-[10%] lg:px-[15%] xl:px-[20%]">
                <div className="h-full lg:border-x lg:border-slate-400 dark:lg:border-slate-600">{children}</div>
              </div>
            </div>
            <ConfirmationModalControl />
            <SnackbarControl />
            <LoadingControl />
          </UserProvider>
        </ThemesProvider>
      </body>
    </html>
  )
}
